drop table teacher1;
drop table student1;
drop sequence sq;
drop trigger tr_insert_st;
drop trigger tr_update_st;
drop trigger tr_delete_st;
drop synonym tchr;
drop synonym stdnt;
drop view vust;
disconnect;
connect;